name: Trips CICD

env:
  # Using ACR
  registry: openhackkz15cji1acr.azurecr.io
  repository: devopsoh/api-trips
# Using Docker Package
#  registry: docker.pkg.github.com
#  repository: hattan/openhack-devops-team-gh/api-trips
  docker_path: apis/trips
  staging_url: https://openhackkz15cji1trips-staging.azurewebsites.net/
  prod_url: https://openhackkz15cji1trips.azurewebsites.net/
  resource_group: openhackkz15cji1rg
  webapp_name: openhackkz15cji1trips
  build_name: Trips
  webv_path: apis/trips/webvalidate

on:
  push:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/trips/**
      - .github/workflows/trips.yml

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.12

    - name: Install dependencies
      run: go get

#    - name: Run Unit Tests
#      run: go test ./tripsgo

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });

  docker_build_and_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:     
    - uses: actions/checkout@v2
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.registry }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}
    # Using ACR
    #- name: Docker login     
    #  run: docker login $registry -u ${{ secrets.ACR_USER }} -p ${{ secrets.ACR_KEY }}
    # Using Github Packages
    #- name: Docker login     
    #  run: docker login $registry -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Docker build
      run: docker build -t ${{ env.registry }}/${{ env.repository }}:${{github.run_number}} --build-arg build_version=${{github.run_number}} ${{ env.docker_path }}

    - name: Docker Push
      run: docker push ${{ env.registry }}/${{ env.repository }}:${{github.run_number}}  

    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });
          
  deploy_to_azure:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: docker_build_and_push
    steps:     
    - uses: actions/checkout@v2
    
    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.registry }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Login Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.webapp_name }}
        slot-name: 'staging'
        images: ${{ env.registry }}/${{ env.repository }}:${{github.run_number}}
        
    - uses: actions/github-script@0.9.0
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n Build Number: ${{ github.run_number }} \n Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) \n";
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",
            body: body
          });